apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: minecraft
          image: 339712756067.dkr.ecr.us-east-1.amazonaws.com/minecraft-server:mc-1.21.4-java21
          ports:
            - containerPort: 25565
          envFrom:
            - configMapRef:
                name: minecraft-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1536Mi"
              cpu: "1000m"
          startupProbe:
            tcpSocket:
              port: 25565
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 0
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: world-data
              mountPath: /data
      volumes:
        - name: world-data
          persistentVolumeClaim:
            claimName: minecraft-world
